# Generated by Django 5.0.6 on 2024-06-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
